config:
  from_address: noreply@rails_sms.com
  
mail_settings:
  delivery_method: snailmail
  port: 2525
  host: railshost
  user: railsuser
  password: railspassword
  authentication: cram_md5

carriers:
  alltel:
    name: Alltel
    value: @rails.message.alltel.com
  ameritech:
    name: Ameritech
    value: @rails.paging.acswireless.com
  at&t: 
    name: AT&T
    value: @rails.txt.att.net
  bell-atlantic: 
    name: Bell Atlantic
    value: @rails.message.bam.com
  bellsouthmobility:
    name: Bellsouth Mobility
    value: @rails.blsdcs.net
  blueskyfrog: 
    name: BlueSkyFrog
    value: @rails.blueskyfrog.com
  boost: 
    name: Boost Mobile
    value: @rails.myboostmobile.com
  cellularsouth: 
    name: Cellular South
    value: @rails.csouth1.com
  comcast: 
    name: Comcast PCS
    value: @rails.comcastpcs.textmsg.com
  cricket: 
    name: Cricket
    value: @rails.sms.mycricket.com
  kajeet: 
    name: kajeet
    value: @rails.mobile.kajeet.net
  metropcs: 
    name: Metro PCS
    value: @rails.mymetropcs.com
  nextel:
    name: Nextel
    value: @rails.messaging.nextel.com
  powertel: 
    name: Powertel
    value: @rails.ptel.net
  pscwireless: 
    name: PSC Wireless
    value: @rails.sms.pscel.com
  qwest: 
    name: Qwest
    value: @rails.qwestmp.com
  southernlink: 
    name: Southern Link
    value: @rails.page.southernlinc.com
  sprint: 
    name: Sprint PCS
    value: @rails.messaging.sprintpcs.com
  suncom: 
    name: Suncom
    value: @rails.tms.suncom.com
  t-mobile: 
    name: T-Mobile
    value: @rails.tmomail.net
  tracfone: 
    name: Tracfone
    value: @rails.mmst5.tracfone.com
  telus-mobility: 
    name: Telus Mobility
    value: @rails.msg.telus.com
  virgin: 
    name: Virgin Mobile
    value: @rails.vmobl.net
  verizon: 
    name: Verizon Wireless
    value: @rails.vtext.com
  # International Carriers
  aliant-canada:
    name: Aliant (Canada)
    value: @rails.chat.wirefree.ca
  beeline-ua: 
    name: Beeline
    value: @rails.sms.beeline.ua
  bellmobility-canada:
    name: Bell Mobility (Canada)
    value: @rails.txt.bell.ca
  bpl-mobile: 
    name: BPL Mobile
    value: @rails.bplmobile.com
  claro-brazil:
    name: Claro (Brazil)
    value: @rails.clarotorpedo.com.br
  claro-nicaragua: 
    name: Claro (Nicaragua)
    value: @rails.ideasclaro-ca.com
  du-arab-emirates: 
    name: Du (UAE)
    value: @rails.email2sms.ae
  e-plus-germany: 
    name: E-Plus (Germany)
    value: @rails.smsmail.eplus.de
  etisalat-arab-emirates: 
    name: Etisalat (UAE)
    value: @rails.email2sms.ae
  fido-canada: 
    name: Fido
    value: @rails.fido.ca
  manitobatelecom-canada:
    name: Manitoba Telecom (Canada)
    value: @rails.text.mtsmobility.com
  mobinil-egypt:
    name: Mobinil
    value: @rails.mobinil.net
  mobistar-belgium: 
    name: Mobistar (Belgium)
    value: @rails.mobistar.be
  mobitel: 
    name: Mobitel
    value: @rails.sms.mobitel.lk
  movistar-spain: 
    name: Movistar (Spain)
    value: @rails.correo.movistar.net
  northerntel-canada:
    name: NorthernTel (Canada)
    value: @rails.txt.northerntelmobility.com
  o2-germany: 
    name: o2 (Germany)
    value: @rails.o2online.de
  o2-uk: 
    name: o2 (UK)
    value: @rails.mmail.co.uk
  orange-mumbai: 
    name: Orange (Mumbai)
    value: @rails.orangemail.co.in
  orange-netherlands: 
    name: Orange (Netherlands)
    value: @rails.sms.orange.nl
  orange-uk: 
    name: Orange (UK)
    value: @rails.orange.net
  rogers-wireless: 
    name: Rogers Wireless
    value: @rails.pcs.rogers.com
  rogers-canada:
    name: Rogers (Canada)
    value: @rails.pcs.rogers.ca
  sasktel-canada:
    name: SaskTel (canada)
    value: @rails.sms.sasktel.ca
  sfr-france: 
    name: SFR (France)
    value: @rails.sfr.fr
  t-mobile-austria: 
    name: T-Mobile (Austria)
    value: @rails.sms.t-mobile.at
  t-mobile-germany: 
    name: T-Mobile (Germany)
    value: @rails.t-d1-sms.de
  t-mobile-germany: 
    name: T-Mobile (Netherlands)
    value: @rails.gin.nl
  t-mobile-uk: 
    name: T-Mobile (UK)
    value: @rails.t-mobile.uk.net
  telebec-canada:
    name: Telebec (Canada)
    value: @rails.txt.telebecmobilite.com
  telefonica-spain: 
    name: Telefonica (Spain)
    value: @rails.movistar.net
  telus-canada:
    name: Telus (Canada)
    value: @rails.msg.telus.com
  virgin-canada:
    name: Virgin (Canada)
    value: @rails.vmobile.ca 
  vodafone-germany: 
    name: Vodafone (Germany)
    value: @rails.vodafone-sms.de
  vodafone-egypt: 
    name: Vodafone (Egypt)
    value: @rails.vodafone.com.eg
  vodafone-uk: 
    name: Vodafone (UK)
    value: @rails.sms.vodafone.net
  vodafone-italy: 
    name: Vodafone (Italy)
    value: @rails.sms.vodafone.it
  vodafone-jp-chuugoku: 
    name: Vodafone (Japan - Chuugoku)
    value: @rails.vodafone.ne.jp
  vodafone-jp-hokkaido: 
    name: Vodafone (Japan - Hokkaido)
    value: @rails.vodafone.ne.jp
  vodafone-jp-hokuriko: 
    name: Vodafone (Japan - Hokuriko)
    value: @rails.vodafone.ne.jp
  vodafone-jp-kansai: 
    name: Vodafone (Japan - Kansai)
    value: @rails.vodafone.ne.jp
  vodafone-jp-osaka: 
    name: Vodafone (Japan - Osaka)
    value: @rails.vodafone.ne.jp
  vodafone-jp-kanto: 
    name: Vodafone (Japan - Kanto)
    value: @rails.vodafone.ne.jp
  vodafone-jp-koushin: 
    name: Vodafone (Japan - Koushin)
    value: @rails.vodafone.ne.jp
  vodafone-jp-tokyo: 
    name: Vodafone (Japan - Tokyo)
    value: @rails.vodafone.ne.jp
  vodafone-jp-kyuushu: 
    name: Vodafone (Japan - Kyuushu)
    value: @rails.vodafone.ne.jp
  vodafone-jp-okinawa: 
    name: Vodafone (Japan - Okinawa)
    value: @rails.vodafone.ne.jp
  vodafone-jp-shikoku: 
    name: Vodafone (Japan - Shikoku)
    value: @rails.vodafone.ne.jp
  vodafone-jp-touhoku: 
    name: Vodafone (Japan - Touhoku)
    value: @rails.vodafone.ne.jp
  vodafone-jp-niigata: 
    name: Vodafone (Japan - Niigata)
    value: @rails.vodafone.ne.jp
  vodafone-jp-toukai: 
    name: Vodafone (Japan - Toukai)
    value: @rails.vodafone.ne.jp
  vodafone-spain: 
    name: Vodafone (Japan - Spain)
    value: @rails.vodafone.es

